#!/usr/bin/env bash

internal_monitor=eDP
ext_monitor_DP="DisplayPort-1"
ext_monitor_HDMI=HDMI1

for i in {1..6}; do
    bspc desktop $i -m $ext_monitor_DP
done
bspc monitor "$ext_monitor_DP" -d 1 2 3 4 5 6
bspc monitor $internal_monitor -d 7 8 9
launchpolybar.sh
xwallpaper --zoom $HOME/.cache/wallpaper.jpg
