#!/bin/sh

setxkbmap -option caps:swapescape pl
autorandr -c &
xwallpaper --zoom $HOME/.cache/wallpaper.jpg
sxhkd &
launchpolybar.sh &
nm-applet &
picom -b --experimental-backends &
flatpak run org.flameshot.Flameshot &
birdtray &
teams &
flatpak run me.kozec.syncthingtk &
flatpak run org.telegram.desktop &
tuxedo-control-center &
megasync &
keepassxc &
calibre -h &
duplicati &
wmname LG3D
$HOME/.local/appimages/Todoist*

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width 1
bspc config window_gap 4

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move
bspc config click_to_focus any
bspc config pointer_follows_monitor true

# Set theme accordingly to actual time
[ -f $HOME/.cache/vim_night ] && night.sh || day.sh
